In [24]:
import numpy as np
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load pre-trained BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = TFBertModel.from_pretrained('bert-base-uncased')

# Sample review texts (you should replace this with actual review data)
reviews = ["The product is excellent!", "Not as good as expected", "Amazing service and quality"]

# BERT tokenization and embedding extraction using CLS token
def get_bert_embeddings(reviews):
    inputs = tokenizer(reviews, return_tensors='tf', padding=True, truncation=True)
    outputs = bert_model(**inputs)
    cls_embedding = outputs.last_hidden_state[:, 0, :]  # Take [CLS] token's embedding
    return cls_embedding

bert_embeddings = get_bert_embeddings(reviews)

# Convert BERT embeddings from tensor to numpy array for splitting
bert_embeddings = bert_embeddings.numpy()

# Sentiment Analysis using BiRNN
class SentimentRNN(tf.keras.Model):
    def __init__(self):
        super(SentimentRNN, self).__init__()
        self.bi_rnn = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64, return_sequences=False))
        self.dense = tf.keras.layers.Dense(1, activation='sigmoid')
    
    def call(self, inputs):
        x = self.bi_rnn(inputs)
        return self.dense(x)

# Create a simple dataset (replace this with actual sentiment labels for your data)
# For example, positive (1) and negative (0) labels for sentiment analysis
labels = np.array([1, 0, 1])  # Example labels corresponding to the reviews

# Ensure the embeddings shape matches the labels shape
assert bert_embeddings.shape[0] == len(labels), "Embedding count does not match label count"

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(bert_embeddings, labels, test_size=0.2)

# Initialize and compile the sentiment model
sentiment_model = SentimentRNN()
sentiment_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model (replace with more epochs and proper dataset for better results)
sentiment_model.fit(X_train, y_train, epochs=10, batch_size=2)

# Make predictions
y_pred = sentiment_model.predict(X_test)

# Print predictions
print(f'Predicted sentiment scores: {y_pred}')

# Evaluate the model (this will show performance on test data)
print(f'Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}')


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Epoch 1/10


ValueError: in user code:

    File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 1398, in train_function  *
        return step_function(self, iterator)
    File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 1370, in run_step  *
        outputs = model.train_step(data)
    File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 1147, in train_step  *
        y_pred = self(x, training=True)
    File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 565, in error_handler  *
        del filtered_tb
    File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 588, in __call__  *
        return super().__call__(*args, **kwargs)
    File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 565, in error_handler  *
        del filtered_tb
    File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/engine/base_layer.py", line 1103, in __call__  *
        input_spec.assert_input_compatibility(
    File "/tmp/__autograph_generated_file9f3ym90m.py", line 495, in tf__assert_input_compatibility
        ag__.if_stmt(ag__.not_(ag__.ld(input_spec)), if_body_25, else_body_25, get_state_30, set_state_30, ('do_return', 'retval_', 'input_spec', 'inputs'), 2)
    File "/tmp/__autograph_generated_file9f3ym90m.py", line 479, in else_body_25
        ag__.for_stmt(ag__.converted_call(ag__.ld(enumerate), (ag__.converted_call(ag__.ld(zip), (ag__.ld(inputs), ag__.ld(input_spec)), None, fscope),), None, fscope), extra_test, loop_body_4, get_state_29, set_state_29, ('do_return', 'retval_'), {'iterate_names': '(input_index, (x, spec))'})
    File "/tmp/__autograph_generated_file9f3ym90m.py", line 463, in loop_body_4
        ag__.if_stmt(ag__.not_(continue__2), if_body_24, else_body_24, get_state_28, set_state_28, ('do_return', 'retval_'), 2)
    File "/tmp/__autograph_generated_file9f3ym90m.py", line 458, in if_body_24
        ag__.if_stmt(ag__.ld(shape).rank is None, if_body_23, else_body_23, get_state_27, set_state_27, ('do_return', 'retval_'), 2)
    File "/tmp/__autograph_generated_file9f3ym90m.py", line 230, in else_body_23
        ag__.if_stmt(ag__.and_(lambda: ag__.ld(spec).ndim is not None, lambda: ag__.not_(ag__.ld(spec).allow_last_axis_squeeze)), if_body_7, else_body_7, get_state_9, set_state_9, (), 0)
    File "/tmp/__autograph_generated_file9f3ym90m.py", line 226, in if_body_7
        ag__.if_stmt(ag__.ld(ndim) != ag__.ld(spec).ndim, if_body_6, else_body_6, get_state_8, set_state_8, (), 0)
    File "/tmp/__autograph_generated_file9f3ym90m.py", line 222, in if_body_6
        raise ag__.converted_call(ag__.ld(ValueError), (f'Input {ag__.ld(input_index)} of layer "{ag__.ld(layer_name)}" is incompatible with the layer: expected ndim={ag__.ld(spec).ndim}, found ndim={ag__.ld(ndim)}. Full shape received: {ag__.converted_call(ag__.ld(tuple), (ag__.ld(shape),), None, fscope)}',), None, fscope)

    ValueError: Exception encountered when calling layer 'sentiment_rnn_13' (type SentimentRNN).
    
    in user code:
    
        File "/tmp/ipykernel_3348346/2605774842.py", line 34, in call  *
            x = self.bi_rnn(inputs)
        File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/layers/rnn/bidirectional.py", line 279, in __call__  *
            return super().__call__(inputs, **kwargs)
        File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 560, in error_handler  *
            filtered_tb = _process_traceback_frames(e.__traceback__)
        File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/engine/base_layer.py", line 1103, in __call__  *
            input_spec.assert_input_compatibility(
        File "/home/triet/ComputerScience_K32/Final_Project/.venv/lib/python3.11/site-packages/tf_keras/src/engine/input_spec.py", line 235, in assert_input_compatibility  *
            raise ValueError(
    
        ValueError: Input 0 of layer "bidirectional_13" is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (2, 768)
    
    
    Call arguments received by layer 'sentiment_rnn_13' (type SentimentRNN):
      • inputs=tf.Tensor(shape=(2, 768), dtype=float32)


In [38]:
import numpy as np
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load pre-trained BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = TFBertModel.from_pretrained('bert-base-uncased')

# Sample review texts (you should replace this with actual review data)
reviews = ["The product is excellent!", "Not as good as expected", "Amazing service and quality", 
           "Terrible experience", "Highly recommended", "Poor quality", "Great value for money", "Very bad"]

# BERT tokenization and embedding extraction using CLS token
def get_bert_embeddings(reviews):
    inputs = tokenizer(reviews, return_tensors='tf', padding=True, truncation=True)
    outputs = bert_model(**inputs)
    cls_embedding = outputs.last_hidden_state[:, 0, :]  # Take [CLS] token's embedding
    return cls_embedding

bert_embeddings = get_bert_embeddings(reviews)

# Convert BERT embeddings from tensor to numpy array for splitting
bert_embeddings = bert_embeddings.numpy()

# Sentiment Analysis using BiRNN
class SentimentRNN(tf.keras.Model):
    def __init__(self):
        super(SentimentRNN, self).__init__()
        self.bi_rnn = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64, return_sequences=False))
        self.dense = tf.keras.layers.Dense(1, activation='sigmoid')
    
    def call(self, inputs):
        # Reshape inputs to (batch_size, sequence_length, feature_size)
        x = tf.expand_dims(inputs, axis=1)  # Add sequence length dimension of 1
        x = self.bi_rnn(x)
        return self.dense(x)

# Create a simple dataset (replace this with actual sentiment labels for your data)
# For example, positive (1) and negative (0) labels for sentiment analysis
labels = np.array([1, 0, 1, 0, 1, 0, 1, 0])  # Example labels corresponding to the reviews

# Ensure the embeddings shape matches the labels shape
assert bert_embeddings.shape[0] == len(labels), "Embedding count does not match label count"

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(bert_embeddings, labels, test_size=0.2)

# Initialize and compile the sentiment model
sentiment_model = SentimentRNN()
sentiment_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model (replace with more epochs and proper dataset for better results)
sentiment_model.fit(X_train, y_train, epochs=10, batch_size=2)

# Now use the trained model to predict sentiment scores on new reviews
new_reviews = ["I love this product!", "good product", "Quality is amazing, but delivery was late."]

# Get BERT embeddings for new reviews
new_bert_embeddings = get_bert_embeddings(new_reviews)
new_bert_embeddings = new_bert_embeddings.numpy()

# Predict sentiment scores using the trained model
sentiment_scores = sentiment_model.predict(new_bert_embeddings)

# Print the predicted sentiment scores
print(f'Predicted sentiment scores: {sentiment_scores}')


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Epoch 1/10
3/3 [==============================] - 2s 4ms/step - loss: 0.8101 - accuracy: 0.6667
Epoch 2/10
3/3 [==============================] - 0s 5ms/step - loss: 0.5776 - accuracy: 0.6667
Epoch 3/10
3/3 [==============================] - 0s 5ms/step - loss: 0.4781 - accuracy: 0.6667
Epoch 4/10
3/3 [==============================] - 0s 5ms/step - loss: 0.4222 - accuracy: 0.6667
Epoch 5/10
3/3 [==============================] - 0s 5ms/step - loss: 0.3342 - accuracy: 1.0000
Epoch 6/10
3/3 [==============================] - 0s 5ms/step - loss: 0.2887 - accuracy: 1.0000
Epoch 7/10
3/3 [==============================] - 0s 5ms/step - loss: 0.2245 - accuracy: 1.0000
Epoch 8/10
3/3 [==============================] - 0s 5ms/step - loss: 0.1714 - accuracy: 1.0000
Epoch 9/10
3/3 [==============================] - 0s 6ms/step - loss: 0.1358 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 498ms/step
Predicted sentiment scores: [[0.96929073]
 [0.92038274]
 [0.89396554]]


In [39]:
# Sample user-item rating matrix (replace with actual data)
rating_matrix = np.array([[5, 3, 0], [4, 0, 0], [1, 5, 4]])  # Example

# Sentiment integration as described in the paper
alpha = 0.5  # Weight for sentiment adjustment

# Adjust ratings with sentiment scores
def update_ratings_with_sentiment(rating_matrix, sentiment_scores, alpha=0.3):
    updated_ratings = np.copy(rating_matrix)
    for i in range(len(rating_matrix)):
        for j in range(len(rating_matrix[i])):
            if rating_matrix[i, j] != 0:
                updated_ratings[i, j] = (1 - alpha) * rating_matrix[i, j] + alpha * sentiment_scores[i]
    return updated_ratings

# Apply sentiment-based adjustment
updated_rating_matrix = update_ratings_with_sentiment(rating_matrix, sentiment_scores)
print("Updated Rating Matrix:", updated_rating_matrix)


Updated Rating Matrix: [[3 2 0]
 [3 0 0]
 [0 3 3]]


In [5]:
from sklearn.decomposition import NMF

# Perform matrix factorization using NMF
nmf_model = NMF(n_components=2)  # 2 latent factors
W = nmf_model.fit_transform(updated_rating_matrix)  # User features
H = nmf_model.components_  # Item features

# Reconstruct the predicted rating matrix
predicted_ratings = np.dot(W, H)
print("Predicted Ratings Matrix:", predicted_ratings)


Predicted Ratings Matrix: [[4.07864278 1.5988613  0.56619288]
 [2.88897235 0.56632645 0.        ]
 [0.         4.07860131 2.88903766]]
